# Generated by Django 6.0.3 on 2026-03-07 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincompose',
            options={},
        ),
        migrations.RemoveField(
            model_name='admincompose',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='admincompose',
            name='source',
        ),
        migrations.AddField(
            model_name='admincompose',
            name='to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admincompose',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
