# Generated by Django 6.0.3 on 2026-03-07 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_admincompose_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincompose',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Message', 'verbose_name_plural': 'Admin Messages'},
        ),
        migrations.AddField(
            model_name='admincompose',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admincompose',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='admincompose',
            name='user',
            field=models.ForeignKey(help_text='User who triggered this message', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
