# Generated by Django 5.2.7 on 2025-11-10 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (you can include +, spaces, or hyphens).', regex='^\\+?\\d[\\d\\s\\-]{9,14}$')]),
        ),
    ]
