# Generated by Django 5.2.7 on 2025-11-10 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format (123)-456-7890', regex='^\\(\\d{3}\\)-\\d{3}-\\d{4}$')]),
        ),
    ]
