# Generated by Django 5.2.7 on 2025-11-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_gold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gold',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
