# Generated by Django 5.2.7 on 2025-11-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_checkingaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckingAccount',
        ),
    ]
