# Generated by Django 5.2.7 on 2025-11-17 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_delete_checkingaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('account_number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
