# Generated by Django 5.2.7 on 2025-11-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_cashaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='account_number',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
