# Generated by Django 5.2.7 on 2025-11-18 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_cashaccount_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashaccount',
            name='account_number',
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to='app1.account'),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
