# Generated by Django 5.2.7 on 2025-11-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_cashaccount_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='account_number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
