# Generated by Django 5.2.7 on 2025-11-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_crypto'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='legal_documents/')),
                ('type', models.CharField(choices=[('PDF', 'PDF'), ('PNG', 'PNG'), ('JPEG', 'JPEG'), ('DOCX', 'DOCX')], default='PDF', max_length=10)),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
    ]
