# Generated by Django 5.2.7 on 2025-11-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_legaldocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingaccount',
            options={'verbose_name': 'CashEquivalent', 'verbose_name_plural': 'CashEquivalents'},
        ),
    ]
