# Generated by Django 5.2.7 on 2025-11-28 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_savingaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Holdings', 'verbose_name_plural': 'Holdings'},
        ),
        migrations.AlterModelOptions(
            name='cashaccount',
            options={'verbose_name': 'Checking Accounts', 'verbose_name_plural': 'Checking Accounts'},
        ),
        migrations.AlterModelOptions(
            name='savingaccount',
            options={'verbose_name': 'Cash Equivalent', 'verbose_name_plural': 'Cash Equivalents'},
        ),
    ]
