# Generated by Django 5.2.7 on 2025-11-29 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_crypto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ssn',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='SSN must be exactly 9 digits')], verbose_name='Social Security Number'),
        ),
    ]
