# Generated by Django 5.2.7 on 2025-12-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_userprofile_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Full address (optional)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_address_on_profile',
            field=models.BooleanField(default=False, help_text='Show address on user profile page'),
        ),
    ]
