# Generated by Django 5.2.7 on 2025-12-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='show_address_on_profile',
        ),
    ]
