# Generated by Django 5.2.10 on 2026-01-07 09:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_remove_userprofile_show_address_on_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format (123)-456-7890', regex='^\\(\\d{3}\\)-\\d{3}-\\d{4}$')])),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')])),
                ('relation', models.CharField(blank=True, help_text='Relationship with account holder', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beneficiary_images/')),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
