# Generated by Django 5.2.10 on 2026-01-07 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_beneficiaryprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='ssn',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='SSN must be exactly 9 digits')], verbose_name='Social Security Number'),
        ),
    ]
