# Generated by Django 5.2.10 on 2026-01-13 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_admincompose'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests_in', to='app1.account'),
        ),
        migrations.AlterField(
            model_name='accounttransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_transfers_out', to='app1.account'),
        ),
        migrations.AlterField(
            model_name='accounttransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_transfers_in', to='app1.account'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_out', to='app1.account'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='to_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer_requests', to='app1.bankaccount'),
        ),
    ]
