# Generated by Django 5.2.10 on 2026-01-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_transferrequest_to_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='avg_buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_price_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
