# Generated by Django 5.2.10 on 2026-01-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='notes',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
