# Generated by Django 5.2.10 on 2026-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
