# Generated by Django 5.2.10 on 2026-02-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashaccounts',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.account'),
        ),
    ]
